# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='intro',
        ),
    ]
